# Site settings
title: "UMD Nexus Cluster Status"
description: "Real-time resource usage monitoring for UMIACS Nexus cluster partitions"
baseurl: ""
url: "https://yourusername.github.io"

# Authentication settings
auth:
  enabled: true
  provider: "github"
  
  # GitHub OAuth settings (you'll need to create a GitHub App)
  github:
    client_id: "your_github_app_client_id"
    # Client secret should be handled server-side or via serverless function
    
    # Authorization settings
    allowed_users:
      - "your-github-username"
      - "colleague-username"
      # Add more GitHub usernames as needed
    
    allowed_organizations:
      - "umiacs"
      - "your-lab-org"
      # Add GitHub organization names
    
    # OAuth scopes required
    scope: "read:user read:org"

# Alternative: Simple token-based auth (less secure but easier)
simple_auth:
  enabled: false
  tokens:
    - "nexus-admin-2024"
    - "lab-member-access"
  
# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Collections
collections:
  data:
    output: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - environment.yml
  - setup.sh

# Custom settings
refresh_interval: 10 # seconds
last_updated_format: "%Y/%b/%-d %H:%M:%S"

# Security headers (for GitHub Pages)
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false